name: PortalGel
main: littlegruz.portalgel.PortalGel
version: 1.3.2
commands:
   portalboots:
      description: Turns on or off the portal boots effect.
      usage: /portalboots <on|off>
   gelplacement:
      description: Turns on or off the placement of gel blocks.
      usage: /gelplacement <on|off>
permissions:
   portalgel.gelplacement:
      description: Allows the placement of blocks
      default: true
   portalgel.portalboots:
      description: Allows the activation of boots
      default: true