name: PortalGel
main: littlegruz.portalgel.PortalGel
version: 1.2
commands:
   portalboots:
      description: Toggles the appearance of a cowsay message on cow death
      usage: /portalboots <on|off>